export const EMAIL_INPUT = 'input[name="email"]'
export const NAME_INPUT = 'input[name*="name"]'
export const PASSWORD_INPUT = 'input[name="password"]'
export const STRIPE_IFRAME = 'iframe[name="embedded-checkout"]'
export const SUBMIT_BTN = 'button[type="submit"]'
export const TOAST_MSG = 'toast-1'
export const TRASH_ICON = 'svg[class*="trash"]'
