name: Lint & Prettier
run-name: Linting on ${{ github.head_ref }}

on:
  pull_request:

jobs:
  lint:
    name: Lint & Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Base setup
        uses: ./.github/workflows/common.yaml
      - name: Format code
        run: yarn format && yarn lint
