name: Lint & Prettier
run-name: Linting on ${{ github.head_ref }}

on:
  pull_request:

jobs:
  setup:
    uses: ./.github/workflows/common.yaml

  lint:
    name: Lint & Prettier
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Format code
        run: yarn format && yarn lint
