name: Types validation
run-name: Validating types on ${{ github.head_ref }}

on:
  pull_request:

jobs:
  setup:
    uses: ./.github/workflows/common.yaml

  types:
    name: Types validation
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Validate types
        run: yarn type:check
